{{- if .Values.externalService }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "es-%s-%s" .Values.externalService.name .Release.Name | trunc 24 }}"
  labels:
{{- if .Values.podLabels}}
  {{- range $key, $value := .Values.podLabels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: ExternalName
  externalName: {{.Values.externalService.externalName }}
  ports:
  - port: {{.Values.externalService.ports }}
{{- end }}
