{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "charts.serviceAccountName" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
{{- if .Values.podLabels}}
  {{- range $key, $value := .Values.podLabels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
