apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
{{- if .Values.podLabels}}
  {{- range $key, $value := .Values.podLabels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- if .Values.podLabels}}
  {{- range $key, $value := .Values.podLabels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}